name: Matrix Demo
on: 
  push:
    branches:
      - master
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-versions: ['16.x','18.x','20.x']
        operating-system: [ubuntu-latest,windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-versions }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
